export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAILURE = "REGISTER_FAILURE"
export const LOGIN_SUCCESS = "LOGIN_SUCCESS"
export const LOGIN_FAILURE = "LOGIN_FAILURE"
export const USER_LOADED = "USER_LOADED"
export const USER_LOADED_FAILED = "USER_LOADED_FAILED"
export const LOG_OUT_USER = "LOG_OUT_USER"