export const REGISTER = "REGISTER";
export const REGISTERFAILURE = "REGISTERFAILURE"
export const LOGIN = "LOGIN"
export const LOGINFAILURE = "LOGINFAILURE"
export const LOADUSER = "LOADUSER"
export const USERLOADEDFAILED = "USERLOADEDFAILED"
export const LOGOUTUSER = "LOGOUTUSER"


export const TOGGLE_CART = "TOGGLE_CART"
export const ADD_TO_CART = "ADD_TO_CART"
export const DELETE_CART_ITEM = "DELETE_CART_ITEM"
export const DECREMENT_CART_QUANTITY = "DECREMENT_CART_QUANTITY"